spring:
  application:
    name: sample-project

  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    driver-class-name: org.postgresql.Driver
    username: user
    password: password

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true