spring:
  application:
    name: sample-project

  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh-secret: ${JWT_REFRESH_SECRET}
  refresh-expiration: 604800000